http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js

# Google Text to speech
tts: !include g_tts.yaml

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Custom Panels
panel_custom:
  - name: Supervisor
    url_path: hassio/system
    sidebar_title: Supervisor
    sidebar_icon: mdi:home-assistant
    module_url: /local/panel-redirect.js

#Google Assistant Free
google_assistant: !include g_assistant_integration.yaml

#Telegram
# telegram_bot:
#   - platform: polling
#     api_key: "7297592306:AAGoJRB3SvXWc6ZG3fOOTfYbMauSs5Q4AN4"
#     allowed_chat_ids:
#       - -687970421
#Telegram Notifier
# notify:
#   - platform: telegram
#     name: "Gigaplex HomeAssistant"
#     chat_id: -687970421

# Custom Sensors
template: !include custom-config/custom_sensors.yaml

#Influx DB
influxdb: !include influxdb.yaml
# Custom Energy
#sensor: !include custom-config/custom_energy.yaml

#Multiscrape
#multiscrape: !include custom-config/multiscrape.yaml
